name: prod
values:
  - key: base_url
    value: ''
    enabled: true
  - key: username
    value: ''
    enabled: true
  - key: password
    value: ''
    enabled: true
  - key: token
    value: ''
    enabled: true
